//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.14 at 04:55:06 오후 KST 
//


package kr.ac.jbnu.ssel.castparser.preference;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}RuleName"/>
 *         &lt;element ref="{}ClassName"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}shouldCheck"/>
 *       &lt;attribute ref="{}type"/>
 *       &lt;attribute ref="{}majorNum"/>
 *       &lt;attribute ref="{}minerNum"/>
 *       &lt;attribute ref="{}category"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "ruleName",
    "className"
})
@XmlRootElement(name = "Rule")
public class Rule {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "RuleName", required = true)
    protected String ruleName;
    @XmlElement(name = "ClassName", required = true)
    protected String className;
    @XmlAttribute(name = "shouldCheck")
    protected Boolean shouldCheck;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "majorNum")
    protected String majorNum;
    @XmlAttribute(name = "minerNum")
    protected String minerNum;
    @XmlAttribute(name = "category")
    protected String category;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ruleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * Sets the value of the ruleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleName(String value) {
        this.ruleName = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the shouldCheck property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShouldCheck() {
        return shouldCheck;
    }

    /**
     * Sets the value of the shouldCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShouldCheck(Boolean value) {
        this.shouldCheck = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the majorNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorNum() {
        return majorNum;
    }

    /**
     * Sets the value of the majorNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorNum(String value) {
        this.majorNum = value;
    }

    /**
     * Gets the value of the minerNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinerNum() {
        return minerNum;
    }

    /**
     * Sets the value of the minerNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinerNum(String value) {
        this.minerNum = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
